# Generated by Django 4.1.3 on 2022-12-13 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_remove_cart_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_payment_details', to='app2.cart'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
