# Generated by Django 4.1.3 on 2022-12-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_paymentdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='cart',
        ),
    ]
