# Generated by Django 4.1.3 on 2022-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Jewellery', 'Jewellery'), ('Kids', 'Kids'), ('Sportswear', 'Sportswear')], max_length=20),
        ),
    ]
