# Generated by Django 4.1.3 on 2022-12-07 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
