# Generated by Django 4.1.3 on 2022-12-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
